-- Core NPI provider (from NPPES npidata). NPI = text PK per project rules.
-- Ultimate goal: parity with full CMS file; start with columns needed for search/join,
-- then add remaining npidata fields in numbered migrations or generated DDL from fileheader.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS core_npi_provider (
  npi CHAR(10) NOT NULL,
  entity_type_code TINYINT NULL,
  replacement_npi CHAR(10) NULL,
  employer_identification_number VARCHAR(20) NULL,
  provider_organization_name VARCHAR(200) NULL,
  provider_last_name VARCHAR(80) NULL,
  provider_first_name VARCHAR(80) NULL,
  provider_middle_name VARCHAR(80) NULL,
  provider_name_prefix VARCHAR(20) NULL,
  provider_name_suffix VARCHAR(20) NULL,
  provider_credential VARCHAR(40) NULL,
  mailing_address_line1 VARCHAR(200) NULL,
  mailing_address_line2 VARCHAR(200) NULL,
  mailing_city VARCHAR(80) NULL,
  mailing_state VARCHAR(40) NULL,
  mailing_postal_code VARCHAR(20) NULL,
  mailing_country VARCHAR(10) NULL,
  mailing_phone VARCHAR(40) NULL,
  mailing_fax VARCHAR(40) NULL,
  practice_address_line1 VARCHAR(200) NULL,
  practice_address_line2 VARCHAR(200) NULL,
  practice_city VARCHAR(80) NULL,
  practice_state VARCHAR(40) NULL,
  practice_postal_code VARCHAR(20) NULL,
  practice_country VARCHAR(10) NULL,
  practice_phone VARCHAR(40) NULL,
  practice_fax VARCHAR(40) NULL,
  enumeration_date DATE NULL,
  last_update_date DATE NULL,
  npi_deactivation_reason_code VARCHAR(10) NULL,
  npi_deactivation_date DATE NULL,
  npi_reactivation_date DATE NULL,
  provider_sex_code CHAR(1) NULL,
  authorized_official_last_name VARCHAR(80) NULL,
  authorized_official_first_name VARCHAR(80) NULL,
  authorized_official_middle_name VARCHAR(80) NULL,
  authorized_official_title VARCHAR(120) NULL,
  authorized_official_phone VARCHAR(40) NULL,
  healthcare_provider_taxonomy_code_1 VARCHAR(20) NULL,
  provider_license_number_1 VARCHAR(40) NULL,
  provider_license_number_state_1 VARCHAR(10) NULL,
  healthcare_provider_primary_taxonomy_switch_1 CHAR(1) NULL,
  healthcare_provider_taxonomy_code_2 VARCHAR(20) NULL,
  provider_license_number_2 VARCHAR(40) NULL,
  provider_license_number_state_2 VARCHAR(10) NULL,
  healthcare_provider_primary_taxonomy_switch_2 CHAR(1) NULL,
  source_batch_id BIGINT UNSIGNED NULL,
  PRIMARY KEY (npi),
  KEY idx_core_npi_practice_state (practice_state),
  KEY idx_core_npi_practice_city (practice_city),
  KEY idx_core_npi_org_name (provider_organization_name(64)),
  KEY idx_core_npi_last_name (provider_last_name(32)),
  KEY idx_core_npi_taxonomy_1 (healthcare_provider_taxonomy_code_1),
  CONSTRAINT fk_core_npi_batch FOREIGN KEY (source_batch_id) REFERENCES ref_source_batch (batch_id)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Primary provider row; extend with ALTER for remaining NPPES columns as needed';
